# Generated by Django 3.2.6 on 2021-08-16 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PracticeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Students_Practice',
        ),
    ]
